### ISSUE TITLE
error occurs when i use gps plugin for openmp

### ISSUE THREAD

**Issue by 0Phucdiamond** [AmyrAhmady/samp-gps-plugin#13]
use plugins folder:
[2023-11-05T13:40:25+0700] [Info] Loading plugin: GPS.dll
[2023-11-05T13:40:25+0700] [Info] This file is not a SA-MP plugin.

use components folder:
Loading component GPS.dll
Failed to load component: it is neither an open.mp component nor a SA-MP plugin.

please help me.
I used google translate to compose this text.

**Comment by 0Phucdiamond** [comment]
@AmyrAhmady @kristoisberg

**Comment by AmyrAhmady** [comment]
fixed, files are updated in latest release
