### ISSUE TITLE
Error plugin load CXXABI_1.3.9

### ISSUE THREAD

**Issue by AbyssMorgan** [AmyrAhmady/samp-gps-plugin#6]
Hi, please make static version for
```
Loading plugin: GPS.so
Failed (/usr/lib/i386-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by plugins/GPS.so))
```
I can't run plugin on host

**Comment by jtylr** [comment]
Having the same issue here, lots of hoops to jump through with getting libstdc++.so.6 in place so we've had to remove the plugin for now.
